# MongoDB local
spring.data.mongodb.uri=mongodb://localhost:27017/delivery
spring.main.allow-bean-definition-overriding=true
server.port=8081
spring.profiles.active=testing
#media.server.api.baseurl=http://localhost:8080/api/v1/media
